spring.application.name=OSapiApplication
spring.datasource.url=jdbc:mysql://172.16.0.30:3306/ghs_osapi?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=ghs
spring.datasource.password=2diSenai
spring.jpa.show-sql=True